# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conektango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(choices=[('AMERICAN_EXPRESS', 'American Express'), ('VISA', 'Visa'), ('MC', 'Master Card')], max_length=20, verbose_name='Tipo de tarjeta'),
        ),
    ]
