# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conektango', '0002_auto_20190803_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('line_items', models.TextField(help_text='En formato JSON', max_length=100000, verbose_name='Líneas de compra')),
                ('currency', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dolar americano')], default='MXN', max_length=3)),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de crédito / débito'), ('oxxo_cash', 'Pago con OXXO')], max_length=20, verbose_name='Método de pago utilizado')),
                ('metadata', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Customer', verbose_name='Cliente')),
                ('payment_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conektango.Card', verbose_name='Tarjeta de crédito / débito')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
    ]
